FROM node:22-alpine AS builder
WORKDIR /app
COPY package*.json tsconfig*.json ./
COPY packages/ packages/
COPY connectors/ connectors/
COPY apps/ apps/
RUN npm install
RUN npm run build

FROM node:22-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production
COPY --from=builder /app ./
EXPOSE 3000
CMD ["npm", "run", "start:api"]
