import { MetricDefinition } from '../types/metric-definition.js';

export const STANDARD_METRICS: MetricDefinition[] = [
  {
    id: 'GROSS_REVENUE',
    titleFa: 'فروش ناخالص',
    titleEn: 'Gross Revenue',
    descriptionFa: 'مجموع ارزش ناخالص فاکتورهای فروش قطعی شده قبل از اعمال تخفیف و مالیات',
    domain: 'SALES',
    dataType: 'CURRENCY_RIAL',
    unitFa: 'ریال',
    unitEn: 'Rial',
    ownerRole: 'CFO',
    formulaExplanationFa: 'مجموع (قیمت واحد × تعداد) کلیه سطرهای فاکتور فروش در وضعیت قطعی',
    formulaExpression: 'SUM(InvoiceLine.grossAmountRial) WHERE Invoice.status != "CANCELLED"',
    sourceEntities: ['Invoice', 'InvoiceLine'],
    dimensions: [
      { id: 'customer', nameFa: 'مشتری', nameEn: 'Customer', sourceEntity: 'Customer', sourceField: 'nameFa' },
      { id: 'product', nameFa: 'محصول', nameEn: 'Product', sourceEntity: 'Product', sourceField: 'nameFa' },
      { id: 'branch', nameFa: 'شعبه / نمایندگی', nameEn: 'Branch', sourceEntity: 'Branch', sourceField: 'titleFa' }
    ],
    defaultTimeGrain: 'MONTHLY_JALALI',
    version: '1.0.0',
    effectiveDateJalali: '1403/01/01',
    approvalStatus: 'APPROVED',
    approvedBy: 'CFO',
    requiresReconciliation: true
  },
  {
    id: 'NET_SALES',
    titleFa: 'فروش خالص',
    titleEn: 'Net Sales',
    descriptionFa: 'فروش ناخالص پس از کسر تخفیفات و برگشت از فروش',
    domain: 'FINANCE',
    dataType: 'CURRENCY_RIAL',
    unitFa: 'ریال',
    unitEn: 'Rial',
    ownerRole: 'CFO',
    formulaExplanationFa: 'فروش ناخالص منهای تخفیفات فاکتور و سطری منهای مبالغ برگشت از فروش',
    formulaExpression: 'SUM(Invoice.totalGrossAmountRial) - SUM(Invoice.totalDiscountAmountRial) - SUM(Return.totalNetAmountRial)',
    sourceEntities: ['Invoice', 'Return'],
    dimensions: [
      { id: 'customer', nameFa: 'مشتری', nameEn: 'Customer', sourceEntity: 'Customer', sourceField: 'nameFa' },
      { id: 'category', nameFa: 'دسته‌بندی محصول', nameEn: 'Category', sourceEntity: 'Category', sourceField: 'titleFa' }
    ],
    defaultTimeGrain: 'MONTHLY_JALALI',
    version: '1.0.0',
    effectiveDateJalali: '1403/01/01',
    approvalStatus: 'APPROVED',
    approvedBy: 'CFO',
    requiresReconciliation: true
  },
  {
    id: 'COGS',
    titleFa: 'بهای تمام‌شده کالای فروش‌رفته',
    titleEn: 'Cost of Goods Sold (COGS)',
    descriptionFa: 'مجموع بهای تمام‌شده مواد، دستمزد مستقیم و سربار جذب‌شده برای محصولات فروش‌رفته',
    domain: 'FINANCE',
    dataType: 'CURRENCY_RIAL',
    unitFa: 'ریال',
    unitEn: 'Rial',
    ownerRole: 'CFO',
    formulaExplanationFa: 'مجموع بهای تمام‌شده در کاردکس خروج انبار برای فاکتورهای فروش',
    formulaExpression: 'SUM(InvoiceLine.cogsAmountRial)',
    sourceEntities: ['InvoiceLine', 'InventoryMovement'],
    dimensions: [
      { id: 'product', nameFa: 'محصول', nameEn: 'Product', sourceEntity: 'Product', sourceField: 'nameFa' }
    ],
    defaultTimeGrain: 'MONTHLY_JALALI',
    version: '1.0.0',
    effectiveDateJalali: '1403/01/01',
    approvalStatus: 'APPROVED',
    approvedBy: 'CFO',
    requiresReconciliation: true
  },
  {
    id: 'GROSS_PROFIT',
    titleFa: 'سود ناخالص',
    titleEn: 'Gross Profit',
    descriptionFa: 'تفاضل فروش خالص از بهای تمام‌شده کالای فروش‌رفته',
    domain: 'FINANCE',
    dataType: 'CURRENCY_RIAL',
    unitFa: 'ریال',
    unitEn: 'Rial',
    ownerRole: 'CFO',
    formulaExplanationFa: 'فروش خالص منهای بهای تمام‌شده کالای فروش‌رفته (COGS)',
    formulaExpression: 'NET_SALES - COGS',
    sourceEntities: ['Invoice', 'InvoiceLine'],
    dimensions: [
      { id: 'product', nameFa: 'محصول', nameEn: 'Product', sourceEntity: 'Product', sourceField: 'nameFa' }
    ],
    defaultTimeGrain: 'MONTHLY_JALALI',
    version: '1.0.0',
    effectiveDateJalali: '1403/01/01',
    approvalStatus: 'APPROVED',
    approvedBy: 'CFO',
    requiresReconciliation: true
  },
  {
    id: 'GROSS_MARGIN_PERCENT',
    titleFa: 'حاشیه سود ناخالص',
    titleEn: 'Gross Margin %',
    descriptionFa: 'نسبت سود ناخالص به فروش خالص',
    domain: 'FINANCE',
    dataType: 'PERCENTAGE',
    unitFa: 'درصد',
    unitEn: '%',
    ownerRole: 'CFO',
    formulaExplanationFa: '(سود ناخالص تقسیم بر فروش خالص) × ۱۰۰',
    formulaExpression: '(GROSS_PROFIT / NET_SALES) * 100',
    sourceEntities: ['Invoice', 'InvoiceLine'],
    dimensions: [
      { id: 'product', nameFa: 'محصول', nameEn: 'Product', sourceEntity: 'Product', sourceField: 'nameFa' }
    ],
    defaultTimeGrain: 'MONTHLY_JALALI',
    version: '1.0.0',
    effectiveDateJalali: '1403/01/01',
    approvalStatus: 'APPROVED',
    approvedBy: 'CFO',
    requiresReconciliation: true
  },
  {
    id: 'CASH_POSITION',
    titleFa: 'موجودی نقد و بانک',
    titleEn: 'Cash & Bank Position',
    descriptionFa: 'مجموع مانده نقدی در تمامی حساب‌های بانکی ریالی و ارزی و صندوق‌های تنخواه سازمان',
    domain: 'TREASURY',
    dataType: 'CURRENCY_RIAL',
    unitFa: 'ریال',
    unitEn: 'Rial',
    ownerRole: 'CFO',
    formulaExplanationFa: 'مجموع مانده حساب‌های بانکی فعال به اضافه مانده صندوق‌های تنخواه',
    formulaExpression: 'SUM(BankAccount.currentBalanceRial) + SUM(CashAccount.currentBalanceRial)',
    sourceEntities: ['BankAccount', 'CashAccount'],
    dimensions: [
      { id: 'bank', nameFa: 'بانک', nameEn: 'Bank', sourceEntity: 'BankAccount', sourceField: 'bankNameFa' }
    ],
    defaultTimeGrain: 'DAILY',
    version: '1.0.0',
    effectiveDateJalali: '1403/01/01',
    approvalStatus: 'APPROVED',
    approvedBy: 'CFO',
    requiresReconciliation: true
  },
  {
    id: 'ACCOUNTS_RECEIVABLE',
    titleFa: 'کل مطالبات تجاری (حساب‌های دریافتنی)',
    titleEn: 'Accounts Receivable',
    descriptionFa: 'مجموع کل مطالبات سررسیدشده و سررسیدنیافته از مشتریان بابت فاکتورهای فروش',
    domain: 'TREASURY',
    dataType: 'CURRENCY_RIAL',
    unitFa: 'ریال',
    unitEn: 'Rial',
    ownerRole: 'CFO',
    formulaExplanationFa: 'مجموع مانده فاکتورهای پرداخت‌نشده از طرف مشتریان',
    formulaExpression: 'SUM(Receivable.remainingAmountRial)',
    sourceEntities: ['Receivable'],
    dimensions: [
      { id: 'customer', nameFa: 'مشتری', nameEn: 'Customer', sourceEntity: 'Customer', sourceField: 'nameFa' },
      { id: 'aging', nameFa: 'بازه سنی مطالبات', nameEn: 'Aging Bucket', sourceEntity: 'Receivable', sourceField: 'agingBucket' }
    ],
    defaultTimeGrain: 'DAILY',
    version: '1.0.0',
    effectiveDateJalali: '1403/01/01',
    approvalStatus: 'APPROVED',
    approvedBy: 'CFO',
    requiresReconciliation: true
  },
  {
    id: 'OVERDUE_RECEIVABLES',
    titleFa: 'مطالبات معوق و سوخت‌شده',
    titleEn: 'Overdue Receivables',
    descriptionFa: 'مجموع مطالبات تجاری که از تاریخ سررسید آن‌ها گذشته است',
    domain: 'TREASURY',
    dataType: 'CURRENCY_RIAL',
    unitFa: 'ریال',
    unitEn: 'Rial',
    ownerRole: 'CFO',
    formulaExplanationFa: 'مجموع مانده فاکتورهایی که تاریخ سررسید آن‌ها قبل از تاریخ امروز است',
    formulaExpression: 'SUM(Receivable.remainingAmountRial) WHERE overdueDays > 0',
    sourceEntities: ['Receivable'],
    dimensions: [
      { id: 'customer', nameFa: 'مشتری', nameEn: 'Customer', sourceEntity: 'Customer', sourceField: 'nameFa' }
    ],
    defaultTimeGrain: 'DAILY',
    version: '1.0.0',
    effectiveDateJalali: '1403/01/01',
    approvalStatus: 'APPROVED',
    approvedBy: 'CFO',
    requiresReconciliation: true
  },
  {
    id: 'DSO',
    titleFa: 'دوره وصول مطالبات (DSO)',
    titleEn: 'Days Sales Outstanding (DSO)',
    descriptionFa: 'متوسط تعداد روزهایی که طول می‌کشد تا وجه حاصل از فروش وصول گردد',
    domain: 'TREASURY',
    dataType: 'RATIO',
    unitFa: 'روز',
    unitEn: 'Days',
    ownerRole: 'CFO',
    formulaExplanationFa: '(کل مطالبات جاری تقسیم بر فروش خالص دوره) × تعداد روزهای دوره (۳۰ روز)',
    formulaExpression: '(ACCOUNTS_RECEIVABLE / NET_SALES) * 30',
    sourceEntities: ['Receivable', 'Invoice'],
    dimensions: [],
    defaultTimeGrain: 'MONTHLY_JALALI',
    version: '1.0.0',
    effectiveDateJalali: '1403/01/01',
    approvalStatus: 'APPROVED',
    approvedBy: 'CFO',
    requiresReconciliation: false
  },
  {
    id: 'INVENTORY_VALUE',
    titleFa: 'ارزش کل موجودی انبار',
    titleEn: 'Total Inventory Value',
    descriptionFa: 'ارزش ریالی موجودی کالا در انبارهای مواد اولیه، کالای در جریان ساخت و محصول نهایی بر اساس روش میانگین موزون/FIFO',
    domain: 'INVENTORY',
    dataType: 'CURRENCY_RIAL',
    unitFa: 'ریال',
    unitEn: 'Rial',
    ownerRole: 'CFO',
    formulaExplanationFa: 'مجموع (موجودی لحظه‌ای × بهای تمام‌شده واحد) در کلیه انبارها',
    formulaExpression: 'SUM(InventoryItem.totalValueRial)',
    sourceEntities: ['InventoryItem', 'Warehouse'],
    dimensions: [
      { id: 'warehouse', nameFa: 'انبار', nameEn: 'Warehouse', sourceEntity: 'Warehouse', sourceField: 'titleFa' },
      { id: 'category', nameFa: 'دسته‌بندی', nameEn: 'Category', sourceEntity: 'Category', sourceField: 'titleFa' }
    ],
    defaultTimeGrain: 'DAILY',
    version: '1.0.0',
    effectiveDateJalali: '1403/01/01',
    approvalStatus: 'APPROVED',
    approvedBy: 'CFO',
    requiresReconciliation: true
  },
  {
    id: 'OEE',
    titleFa: 'اثربخشی کلی تجهیزات (OEE)',
    titleEn: 'Overall Equipment Effectiveness (OEE)',
    descriptionFa: 'معیار جامع بهره‌وری خطوط تولید حاصل‌ضرب سه نرخ: در دسترس بودن، عملکرد و کیفیت',
    domain: 'MANUFACTURING',
    dataType: 'PERCENTAGE',
    unitFa: 'درصد',
    unitEn: '%',
    ownerRole: 'COO',
    formulaExplanationFa: 'در دسترس بودن (Availability) × راندمان عملکرد (Performance) × نرخ کیفیت (Quality Rate)',
    formulaExpression: 'Availability * Performance * Quality',
    sourceEntities: ['Machine', 'Downtime', 'ProductionOrder', 'QualityInspection'],
    dimensions: [
      { id: 'machine', nameFa: 'دستگاه / خط تولید', nameEn: 'Machine', sourceEntity: 'Machine', sourceField: 'titleFa' },
      { id: 'workCenter', nameFa: 'ایستگاه کاری', nameEn: 'Work Center', sourceEntity: 'WorkCenter', sourceField: 'titleFa' }
    ],
    defaultTimeGrain: 'DAILY',
    version: '1.0.0',
    effectiveDateJalali: '1403/01/01',
    approvalStatus: 'APPROVED',
    approvedBy: 'COO',
    requiresReconciliation: false
  },
  {
    id: 'PRODUCTION_SCRAP_RATE',
    titleFa: 'نرخ ضایعات تولید',
    titleEn: 'Production Scrap Rate %',
    descriptionFa: 'درصد کل قطعات/محصولات ضایعاتی نسبت به کل حجم تولید شده',
    domain: 'QUALITY',
    dataType: 'PERCENTAGE',
    unitFa: 'درصد',
    unitEn: '%',
    ownerRole: 'COO',
    formulaExplanationFa: '(مجموع تعداد ضایعات تقسیم بر کل تعداد تولید شده) × ۱۰۰',
    formulaExpression: '(SUM(QualityInspection.rejectedQty) / SUM(ProductionOrder.producedQuantity)) * 100',
    sourceEntities: ['QualityInspection', 'ProductionOrder'],
    dimensions: [
      { id: 'product', nameFa: 'محصول', nameEn: 'Product', sourceEntity: 'Product', sourceField: 'nameFa' },
      { id: 'workCenter', nameFa: 'ایستگاه کاری', nameEn: 'Work Center', sourceEntity: 'WorkCenter', sourceField: 'titleFa' }
    ],
    defaultTimeGrain: 'MONTHLY_JALALI',
    version: '1.0.0',
    effectiveDateJalali: '1403/01/01',
    approvalStatus: 'APPROVED',
    approvedBy: 'COO',
    requiresReconciliation: false
  },
  {
    id: 'MACHINE_DOWNTIME_HOURS',
    titleFa: 'ساعات توقف خطوط و ماشین‌آلات',
    titleEn: 'Machine Downtime Hours',
    descriptionFa: 'مجموع کل ساعات توقف ناشی از خرابی اضطراری، قطعی برق، نبود مواد اولیه یا تنظیم قالب',
    domain: 'MAINTENANCE',
    dataType: 'DURATION_HOURS',
    unitFa: 'ساعت',
    unitEn: 'Hours',
    ownerRole: 'COO',
    formulaExplanationFa: 'مجموع دقایق توقف ثبت‌شده در سیستم نگهداری و تعمیرات تقسیم بر ۶۰',
    formulaExpression: 'SUM(Downtime.durationMinutes) / 60',
    sourceEntities: ['Downtime', 'Machine'],
    dimensions: [
      { id: 'reason', nameFa: 'علت توقف', nameEn: 'Downtime Reason', sourceEntity: 'Downtime', sourceField: 'reasonFa' },
      { id: 'machine', nameFa: 'دستگاه', nameEn: 'Machine', sourceEntity: 'Machine', sourceField: 'titleFa' }
    ],
    defaultTimeGrain: 'MONTHLY_JALALI',
    version: '1.0.0',
    effectiveDateJalali: '1403/01/01',
    approvalStatus: 'APPROVED',
    approvedBy: 'COO',
    requiresReconciliation: false
  },
  {
    id: 'PLAN_ATTAINMENT',
    titleFa: 'درصد تحقق برنامه تولید',
    titleEn: 'Production Plan Attainment %',
    descriptionFa: 'نسبت مقدار واقعی تولید شده به مقدار برنامه‌ریزی‌شده در بازه زمانی معین',
    domain: 'MANUFACTURING',
    dataType: 'PERCENTAGE',
    unitFa: 'درصد',
    unitEn: '%',
    ownerRole: 'COO',
    formulaExplanationFa: '(مجموع تولید واقعی تقسیم بر مجموع برنامه تولید مصوب) × ۱۰۰',
    formulaExpression: '(SUM(ProductionOrder.producedQuantity) / SUM(ProductionOrder.plannedQuantity)) * 100',
    sourceEntities: ['ProductionOrder'],
    dimensions: [
      { id: 'product', nameFa: 'محصول', nameEn: 'Product', sourceEntity: 'Product', sourceField: 'nameFa' }
    ],
    defaultTimeGrain: 'MONTHLY_JALALI',
    version: '1.0.0',
    effectiveDateJalali: '1403/01/01',
    approvalStatus: 'APPROVED',
    approvedBy: 'COO',
    requiresReconciliation: false
  }
];
